@ECHO OFF&&SETLOCAL ENABLEDELAYEDEXPANSION&&CD /D %~DP0&&Reg.exe query "HKU\S-1-5-19\Environment">NUL
IF NOT %ERRORLEVEL% EQU 0 ECHO Right-Click ^& Run As Administrator&&PAUSE&&EXIT 0
SET "PROG_SOURCE=%CD%"&&SET "PROG_TARGET=%CD%"&&SET "PACK_COMPRESS=FAST"&&COLOR 0B
SET DRVTAR=%SYSTEMDRIVE%&&SET WINTAR=%WINDIR%&&SET USRTAR=%USERPROFILE%
SET HIVE_USER=HKCU&&SET HIVE_SOFTWARE=HKLM\SOFTWARE&&SET HIVE_SYSTEM=HKLM\SYSTEM
FOR /F "delims=" %%G in ('CMD.EXE /D /U /C ECHO %PROG_SOURCE%^| FIND /V ""') do (IF "%%G"==" " ECHO Remove the space from the Folder-Name, then launch again&&PAUSE&&EXIT 0)
FOR %%a in (1 2 3 4 5) DO (IF EXIST "%PROG_SOURCE%\Project%%a" SET "MAKER_SLOT=%%a"&&SET "MAKER_FOLDER=%PROG_SOURCE%\Project%%a")
IF NOT DEFINED MAKER_SLOT SET MAKER_SLOT=1&&SET "MAKER_FOLDER=%PROG_SOURCE%\Project1"
:MAKER_START
CLS&&CALL:PAD_LINE
ECHO                      Josh's $PK Package Creator&&CALL:PAD_LINE
FOR %%a in (PackName PackType PackTag PackDesc REG_KEY REG_VAL RUN_MOD REG_DAT) DO (CALL SET "%%a=NULL")
IF EXIST "%MAKER_FOLDER%\PACKAGE.$HZ" FOR /F "eol=- TOKENS=1-2 delims==" %%a in (%MAKER_FOLDER%\PACKAGE.$HZ) DO (IF NOT "%%a"=="   " SET "%%a=%%b")
IF NOT "%REG_KEY%"=="NULL" IF NOT "%REG_VAL%"=="NULL" IF NOT "%RUN_MOD%"=="NULL" IF NOT "%REG_DAT%"=="NULL" SET PACK_COND=ENABLED
IF "%REG_KEY%"=="NULL" SET PACK_COND=DISABLED
IF "%REG_VAL%"=="NULL" SET PACK_COND=DISABLED
IF "%RUN_MOD%"=="NULL" SET PACK_COND=DISABLED
IF "%REG_DAT%"=="NULL" SET PACK_COND=DISABLED
IF NOT "%REG_VAL%"=="NULL" IF NOT "%RUN_MOD%"=="NULL" IF NOT "%REG_DAT%"=="NULL" SET PACK_COND=ENABLED
IF NOT DEFINED PROG_OPER IF "%PACK_COND%"=="ENABLED" ECHO  [Name[%PackName%] [Type[%PackType%] [Tag[%PackTag%] [X-LVL[%PACK_COMPRESS%] [PMT[%PACK_COND%]&&CALL:PAD_LINE
IF NOT DEFINED PROG_OPER IF "%PACK_COND%"=="DISABLED" ECHO  [Name[%PackName%] [Type[%PackType%] [Tag[%PackTag%] [X-LVL[%PACK_COMPRESS%]&&CALL:PAD_LINE
IF NOT DEFINED PROG_OPER ECHO  [Desc]: %PackDesc%&&CALL:PAD_LINE
IF NOT DEFINED PROG_OPER IF "%PACK_COND%"=="ENABLED" ECHO   PERMIT IF: [%REG_KEY% %REG_VAL%] [%RUN_MOD%] [%REG_DAT%]&&CALL:PAD_LINE
IF NOT DEFINED PROG_OPER SET "LIST_DIR=%MAKER_FOLDER%\*.*"&&SET LIST_FMT=PLAIN&&ECHO   PACKAGE CONTENTS:&&ECHO.&&CALL:FILE_LIST&&CALL:PAD_LINE
IF "%PROG_OPER%"=="MAKER_RESTORE" SET "LIST_DIR=%PACK_FOLDER%\*.$PK"&&SET LIST_FMT=NUMERAL&&ECHO   AVAILABLE $PK'S:&&ECHO.&&CALL:FILE_LIST&&CALL:PAD_LINE
IF NOT DEFINED PROG_OPER IF NOT DEFINED PackType ECHO  {X}PROJECT[%MAKER_SLOT%] {R}estore {N}ew Template {E}xport-Drivers {*}Examples&&CALL:PAD_LINE
IF NOT DEFINED PROG_OPER IF "%PackType%"=="NULL" ECHO  {X}PROJECT[%MAKER_SLOT%] {R}estore {N}ew Template {E}xport-Drivers {*}Examples&&CALL:PAD_LINE
IF NOT DEFINED PROG_OPER IF "%PackType%"=="DRIVER" ECHO  {X}PROJECT[%MAKER_SLOT%]   {V}iew/Edit  {Z}Compression  {I}nspect-System&&CALL:PAD_LINE
IF NOT DEFINED PROG_OPER IF "%PackType%"=="DRIVER" ECHO      {C}reate  {R}estore  {N}ew Template  {E}xport-Drivers {P}ermit&&CALL:PAD_LINE
IF NOT DEFINED PROG_OPER IF "%PackType%"=="SCRIPTED" ECHO  {X}PROJECT[%MAKER_SLOT%]  {V}iew/Edit  {Z}Compression  {P}ermit&&CALL:PAD_LINE
IF NOT DEFINED PROG_OPER IF "%PackType%"=="SCRIPTED" ECHO         {C}reate    {R}estore    {N}ew Template    {*}Examples&&CALL:PAD_LINE
IF NOT DEFINED PROG_OPER IF "%PackType%"=="STORAGE" ECHO  {X}PROJECT[%MAKER_SLOT%]      {V}iew/Edit  {Z}Compression  {P}ermit&&CALL:PAD_LINE
IF NOT DEFINED PROG_OPER IF "%PackType%"=="STORAGE" ECHO        {C}reate   {R}estore   {N}ew Template   {*}Examples&&CALL:PAD_LINE
IF DEFINED PROG_OPER ECHO                  Enter File # To [%PROG_OPER%] {/}Type&&CALL:PAD_LINE
ECHO                Press (Enter) to Return to Previous Menu
CALL:MENU_SELECT&&IF DEFINED PROG_OPER CALL:FILE_LIST>NUL
IF DEFINED PROG_OPER IF NOT DEFINED SELECT SET PROG_OPER=
IF "%SELECT%"=="C" SET PROG_OPER=MAKER_CREATE
IF "%SELECT%"=="E" IF "%PackType%"=="NULL" SET PROG_OPER=MAKER_EXPORT
IF "%SELECT%"=="E" IF "%PackType%"=="DRIVER" SET PROG_OPER=MAKER_EXPORT
IF "%SELECT%"=="*" SET PROG_OPER=MAKER_EXAMPLE
IF "%SELECT%"=="I" SET PROG_OPER=MAKER_INSPECT
IF "%SELECT%"=="N" SET PROG_OPER=MAKER_TEMPLATE
IF "%SELECT%"=="R" SET PROG_OPER=MAKER_RESTORE&&GOTO:MAKER_START
IF "%SELECT%"=="P" CALL:PACK_COND
IF "%SELECT%"=="X" CALL:MAKER_SLOT
IF "%SELECT%"=="Z" CALL:PACK_COMPRESS
IF "%SELECT%"=="V" SET "EDIT_SETUP=1"&&SET "EDIT_MANIFEST=1"&&SET "EDIT_README=1"&&SET "EDIT_CUSTOM="&&CALL:MAKER_EDITOR
IF "%PROG_OPER%"=="MAKER_RESTORE" IF NOT DEFINED SELECT SET PROG_OPER=&&GOTO:MAKER_START
IF "%PROG_OPER%"=="MAKER_RESTORE" IF NOT EXIST "%PACK_FOLDER%\%SELECT%" GOTO:MAKER_START
IF DEFINED PROG_OPER SET "SCRATCHDIR_MAKER=%PROG_SOURCE%\Scratch"
IF DEFINED PROG_OPER IF EXIST "%SCRATCHDIR_MAKER%" DISM /cleanup-MountPoints>NUL 2>&1
IF DEFINED PROG_OPER IF EXIST "%SCRATCHDIR_MAKER%" RD /S /Q "%SCRATCHDIR_MAKER%">NUL 2>&1
IF "%PROG_OPER%"=="MAKER_CREATE" CALL:MAKER_CREATE
IF "%PROG_OPER%"=="MAKER_EXAMPLE" SET EXAMPLE_MODE=CREATE&&CALL:PACKEX_MENU_START
IF "%PROG_OPER%"=="MAKER_EXPORT" SET PackType=DRIVER&&IF "%PackName%"=="NULL" SET PackName=DRIVER_%RANDOM%
IF "%PROG_OPER%"=="MAKER_EXPORT" IF NOT EXIST "%MAKER_FOLDER%" MD "%MAKER_FOLDER%">NUL 2>&1
IF "%PROG_OPER%"=="MAKER_EXPORT" DISM /ONLINE /EXPORT-DRIVER /destination:"%MAKER_FOLDER%"&&CALL:PACK_MANIFEST&&CALL:PAD_LINE&&PAUSE
IF "%PROG_OPER%"=="MAKER_INSPECT" IF "%PackType%"=="DRIVER" DISM /ONLINE /GET-DRIVERS&&CALL:PAD_LINE&&PAUSE
IF "%PROG_OPER%"=="MAKER_RESTORE" ECHO [Project[%MAKER_SLOT%] FOLDER WILL BE CLEARED&&ECHO.PRESS(Z)TO PROCEED&&SET PROMPT_SET=PJ_CLEAR&&CALL:PROMPT_SET
IF "%PROG_OPER%"=="MAKER_RESTORE" IF NOT "%PJ_CLEAR%"=="Z" SET PROG_OPER=&&GOTO:MAKER_START
IF "%PROG_OPER%"=="MAKER_RESTORE" IF NOT EXIST "%SCRATCHDIR_MAKER%" MD "%SCRATCHDIR_MAKER%">NUL 2>&1
IF "%PROG_OPER%"=="MAKER_RESTORE" DISM /APPLY-IMAGE /IMAGEFILE:"%PACK_FOLDER%\%SELECT%" /INDEX:2 /APPLYDIR:"%SCRATCHDIR_MAKER%">NUL 2>&1
IF "%PROG_OPER%"=="MAKER_RESTORE" FOR %%a in (PackName PackType PackDesc PackTag REG_KEY REG_VAL RUN_MOD REG_DAT) DO (CALL SET "%%a=NULL")
IF "%PROG_OPER%"=="MAKER_RESTORE" IF EXIST "%SCRATCHDIR_MAKER%\PACKAGE.$HZ" FOR /F "eol=- TOKENS=1-2 delims==" %%a in (%SCRATCHDIR_MAKER%\PACKAGE.$HZ) DO (IF NOT "%%a"=="   " SET "%%a=%%b")
IF "%PROG_OPER%"=="MAKER_RESTORE" FOR %%a in (PackName PackType PackDesc PackTag REG_KEY REG_VAL RUN_MOD REG_DAT) DO (IF NOT DEFINED %%a CALL SET "%%a=NULL")
IF "%PROG_OPER%"=="MAKER_RESTORE" IF NOT EXIST "%SCRATCHDIR_MAKER%\PACKAGE.$HZ" ECHO PACKAGE %PackName% IS DEFUNCT&&SET PACK_DEFUNCT=1&&PAUSE&&GOTO:MAKER_START
IF "%PROG_OPER%"=="MAKER_RESTORE" IF EXIST "%MAKER_FOLDER%" RD /S /Q "%MAKER_FOLDER%">NUL 2>&1
IF "%PROG_OPER%"=="MAKER_RESTORE" IF NOT EXIST "%MAKER_FOLDER%" MD "%MAKER_FOLDER%">NUL 2>&1
IF "%PROG_OPER%"=="MAKER_RESTORE" MOVE /Y "%SCRATCHDIR_MAKER%\PACKAGE.$HZ" "%MAKER_FOLDER%">NUL 2>&1
IF "%PROG_OPER%"=="MAKER_RESTORE" DISM /APPLY-IMAGE /IMAGEFILE:"%PACK_FOLDER%\%SELECT%" /INDEX:1 /APPLYDIR:"%MAKER_FOLDER%"
IF "%PROG_OPER%"=="MAKER_TEMPLATE" CALL:PACK_TEMPLATE
IF DEFINED PROG_OPER IF EXIST "%SCRATCHDIR_MAKER%" DISM /cleanup-MountPoints>NUL 2>&1
IF DEFINED PROG_OPER IF EXIST "%SCRATCHDIR_MAKER%" RD /S /Q "\\?\%SCRATCHDIR_MAKER%" >NUL 2>&1
IF DEFINED PROG_OPER SET PROG_OPER=
GOTO:MAKER_START
:MAKER_CREATE
CALL:PAD_LINE&&ECHO.                       *Package-Create* START&&CALL:PAD_LINE
SET "SCRATCHDIR_MAKER=%PROG_SOURCE%\Scratch"
IF EXIST "%SCRATCHDIR_MAKER%" DISM /cleanup-MountPoints>NUL 2>&1
IF EXIST "%SCRATCHDIR_MAKER%" RD /S /Q "%SCRATCHDIR_MAKER%">NUL 2>&1
IF NOT EXIST "%MAKER_FOLDER%\*.*" ECHO.Project%MAKER_SLOT% is empty&&PAUSE&&EXIT /B
IF NOT DEFINED PackName ECHO.PackName is Empty&&PAUSE&&EXIT /B
IF NOT DEFINED PackType ECHO.PackType is Empty&&PAUSE&&EXIT /B
IF NOT EXIST "%SCRATCHDIR_MAKER%" MD "%SCRATCHDIR_MAKER%">NUL 2>&1
MOVE /Y "%MAKER_FOLDER%\PACKAGE.$HZ" "%SCRATCHDIR_MAKER%">NUL 2>&1
ECHO.                         *Creating Package*
DISM /CAPTURE-IMAGE /CAPTUREDIR:"%MAKER_FOLDER%" /IMAGEFILE:"%PACK_FOLDER%\%PackName%.$PK" /COMPRESS:%PACK_COMPRESS% /NAME:"%PackName%" /CheckIntegrity /Verify
DISM /APPEND-IMAGE /IMAGEFILE:"%PACK_FOLDER%\%PackName%.$PK" /CAPTUREDIR:"%SCRATCHDIR_MAKER%" /NAME:"%PackName%" /Description:$haZZam^^! /CheckIntegrity /Verify>NUL 2>&1
MOVE /Y "%SCRATCHDIR_MAKER%\PACKAGE.$HZ" "%MAKER_FOLDER%">NUL 2>&1
IF EXIST "%SCRATCHDIR_MAKER%" DISM /cleanup-MountPoints>NUL 2>&1
IF EXIST "%SCRATCHDIR_MAKER%" RD /S /Q "\\?\%SCRATCHDIR_MAKER%" >NUL 2>&1
CALL:PAD_LINE&&ECHO.                       *Package-Create* END&&CALL:PAD_LINE
IF DEFINED PROG_OPER SET PROG_OPER=
EXIT /B
:PAD_LINE
ECHO ====================================================================
EXIT /B
:MENU_SELECT
SET SELECT=&&SET /P "SELECT=$>>"&&FOR %%G in (A B C D E F G H I J K L M N O P Q R S T U V W X Y Z) DO (CALL SET "SELECT=%%SELECT:%%G=%%G%%")
EXIT /B
:PROMPT_SET
ECHO.&&SET PROMPT_VAR=&&SET /P "PROMPT_VAR=$>>"
CALL SET "%PROMPT_SET%=%PROMPT_VAR%"&&SET PROMPT_SET=&&SET PROMPT_VAR=
EXIT /B
:MAKER_SLOT
SET /A MAKER_SLOT+=1
IF NOT DEFINED MAKER_SLOT SET MAKER_SLOT=1
IF "%MAKER_SLOT%" GEQ "6" SET MAKER_SLOT=1
SET "MAKER_FOLDER=%PROG_SOURCE%\Project%MAKER_SLOT%"
EXIT /B
:PACK_COMPRESS
SET SELECT=
IF NOT DEFINED PAK_XXX SET PAK_XXX=1
SET /A PAK_XXX+=1
IF "%PAK_XXX%" GEQ "4" SET PAK_XXX=1
IF "%PAK_XXX%"=="1" SET PACK_COMPRESS=FAST
IF "%PAK_XXX%"=="2" SET PACK_COMPRESS=MAX
IF "%PAK_XXX%"=="3" SET PACK_COMPRESS=NONE
EXIT /B
:PACK_COND
CALL ECHO INPUT REG-KEY&&ECHO (CASE SENSITIVE^^!)&&SET PROMPT_SET=SELECT&&CALL:PROMPT_SET
CALL SET "REG_KEY=%SELECT%"
IF NOT DEFINED REG_KEY SET REG_VAL=&&SET RUN_MOD=&&SET REG_DAT=&&CALL:PACK_MANIFEST&&EXIT /B
CALL ECHO INPUT REG-VALUE&&ECHO (CASE SENSITIVE^^!)&&SET PROMPT_SET=SELECT&&CALL:PROMPT_SET
CALL SET "REG_VAL=%SELECT%"
IF NOT DEFINED REG_VAL EXIT /B
CALL REG QUERY "%REG_KEY%" /V "%REG_VAL%" >$HZ.TXT
SET COL1=&&IF EXIST $HZ.TXT FOR /F "TOKENS=* DELIMS=" %%1 in ($HZ.TXT) DO (SET COL1=%%1)
CALL ECHO [%COL1%]&&DEL $HZ.TXT>NUL 2>&1
CALL ECHO INPUT REG-VALUE TARGET DATA&&ECHO (CASE SENSITIVE^^!)&&SET PROMPT_SET=SELECT&&CALL:PROMPT_SET
CALL SET "REG_DAT=%SELECT%"
ECHO PERMIT INSTALL IF DATA&&ECHO {1}MATCH&&ECHO {2}DOES NOT MATCH&&CALL:MENU_SELECT
IF NOT DEFINED SELECT SET "RUN_MOD=EQU"
IF "%SELECT%"=="1" SET "RUN_MOD=EQU"
IF "%SELECT%"=="2" SET "RUN_MOD=NEQ"
CALL:PACK_MANIFEST
EXIT /B
:MAKER_EDITOR
IF DEFINED EDIT_SETUP IF EXIST "%MAKER_FOLDER%\PACKAGE.CMD" START NOTEPAD.EXE "%MAKER_FOLDER%\PACKAGE.CMD"
IF DEFINED EDIT_MANIFEST IF EXIST "%MAKER_FOLDER%\PACKAGE.$HZ" START NOTEPAD.EXE "%MAKER_FOLDER%\PACKAGE.$HZ"
IF DEFINED EDIT_README IF EXIST "%MAKER_FOLDER%\README.TXT" START NOTEPAD.EXE "%MAKER_FOLDER%\README.TXT"
IF DEFINED EDIT_CUSTOM IF EXIST "%MAKER_FOLDER%\%EDIT_CUSTOM%" START NOTEPAD.EXE "%MAKER_FOLDER%\%EDIT_CUSTOM%"
SET EDIT_SETUP=&&SET EDIT_MANIFEST=&&SET EDIT_README=&&SET EDIT_CUSTOM=
EXIT /B
:PACK_TEMPLATE
ECHO FOLDER[Project%MAKER_SLOT%] WILL BE CLEARED&&ECHO.PRESS{Z}TO PROCEED&&CALL:MENU_SELECT
IF NOT "%SELECT%"=="Z" EXIT /B
FOR %%a in (PackName PackType PackDesc PackTag REG_KEY REG_VAL RUN_MOD REG_DAT) DO (CALL SET "%%a=")
ECHO Type of Pack?&&ECHO. {1}SCRIPTED&&ECHO. {2}DRIVER&&ECHO. {3}STORAGE&&CALL:MENU_SELECT
IF "%SELECT%"=="1" SET PackType=SCRIPTED
IF "%SELECT%"=="2" SET PackType=DRIVER
IF "%SELECT%"=="3" SET PackType=STORAGE
IF NOT DEFINED PackType EXIT /B
ECHO Name of Pack?&&CALL SET "PROMPT_SET=PackName"&&CALL:PROMPT_SET
IF NOT DEFINED PackName EXIT /B
DISM /cleanup-MountPoints>NUL 2>&1
ECHO Description?&&CALL SET "PROMPT_SET=PackDesc"&&CALL:PROMPT_SET
IF EXIST "%MAKER_FOLDER%" RD /S /Q "%MAKER_FOLDER%">NUL 2>&1
IF NOT EXIST "%MAKER_FOLDER%" MD "%MAKER_FOLDER%">NUL 2>&1
ECHO.>"%MAKER_FOLDER%\PACKAGE.$HZ"&&CALL:PACK_MANIFEST
IF "%PackType%"=="SCRIPTED" CALL:PACK_VARS&&CALL:PACK_END
EXIT /B
:FILE_LIST
IF DEFINED LIST_DIR IF EXIST "%LIST_DIR%" SET LIST_CNT=0&&DIR "%LIST_DIR%" /A: /B /O:GN>%TEMP%\$HZ.TXT&&FOR /F "TOKENS=*" %%a in (%TEMP%\$HZ.TXT) DO (CALL SET /A LIST_CNT+=1&&CALL SET "OBJ_NAME=%%a"&&CALL:FILE_LIST_OUTSIDE)
IF DEFINED LIST_DIR IF NOT EXIST "%LIST_DIR%" ECHO  [CRICKETS..]
ECHO.&&SET LIST_DIR=&&SET LIST_TXT=&&SET LIST_FMT=&&SET FILE_LIST_EXT=&&IF EXIST "%TEMP%\$HZ.TXT" DEL /F "%TEMP%\$HZ.TXT">NUL 2>&1
IF "%SELECT%"=="\" CALL:MENU_SELECT&&EXIT /B
IF "%SELECT%"=="/" CALL:MENU_SELECT&&EXIT /B
CALL SET "SELECT=%%TEMP_NAME%SELECT%%%"
CALL SET "LIST_OUTPUT=%%TEMP_NAME%SELECT%%%"
EXIT /B
:FILE_LIST_OUTSIDE
CALL SET "TEMP_NAME%LIST_CNT%=%OBJ_NAME%"
IF "%LIST_FMT%"=="NUMERAL" ECHO  [ %LIST_CNT% ]\[%OBJ_NAME%]
IF "%LIST_FMT%"=="PLAIN" ECHO  [SRC]\[%OBJ_NAME%]
EXIT /B
:PAD_LINE
ECHO ====================================================================
EXIT /B
:PAK_LOAD
FOR %%a in (PackName PackType PackDesc PackTag REG_KEY REG_VAL RUN_MOD REG_DAT) DO (CALL SET %%a=NULL)
IF EXIST "%MAKER_FOLDER%\PACKAGE.$HZ" COPY /Y "%MAKER_FOLDER%\PACKAGE.$HZ" "%TEMP%\0002"&&FOR /F "eol=- TOKENS=1-2 delims==" %%a in (%TEMP%\0002) DO (IF NOT "%%a"=="   " SET "%%a=%%b")
DEL /Q /F "%TEMP%\0002">NUL 2>&1
EXIT /B
:PACK_SAVE
MOVE /Y "%MAKER_FOLDER%\PACKAGE.$HZ" "%TEMP%\0002"&&FOR /F "eol=- TOKENS=1-2 delims==" %%a in (%TEMP%\0002) DO (CALL ECHO %%a=%%%%a%%>>"%MAKER_FOLDER%\PACKAGE.$HZ")
DEL /Q /F "%TEMP%\0002">NUL 2>&1
EXIT /B
:PACK_MANIFEST
FOR %%a in (PackName PackType PackDesc PackTag REG_KEY REG_VAL RUN_MOD REG_DAT) DO (IF NOT DEFINED %%a CALL SET %%a=NULL)
(
ECHO ----------[Package Manifest]---------=
ECHO.PackName=%PackName%
ECHO.PackType=%PackType%
ECHO.PackDesc=%PackDesc%
ECHO.PackTag=%PackTag%
ECHO.REG_KEY=%REG_KEY%
ECHO.REG_VAL=%REG_VAL%
ECHO.RUN_MOD=%RUN_MOD%
ECHO.REG_DAT=%REG_DAT%
ECHO.Created=%date% %time%
ECHO ------------[END OF FILE]------------=
)>"%MAKER_FOLDER%\PACKAGE.$HZ"
EXIT /B
:PACK_VARS
ECHO;:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;::THE REGISTRY/FILES ARE NORMAL DURING SETUPCOMPLETE,RUNONCE,^& LISTMGR ::>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;::         DURING THE IMAGE-APPLY THEY ARE EXTERNALLY MOUNTED          ::>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;::  IMAGE-APPLY=OFFLINE, SETUP-COMPLETE=PRE-LOGON, RUN-ONCE=1ST LOGON  ::>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;:: THESE VARIABLES ARE BUILT-IN AND CAN HELP KEEP A SCRIPT CONSISTANT  ::>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;::      THROUGHOUT THE ENTIRE PROCESS AND FOR LIVE-PACKAGE APPLY       ::>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;::       FOLDER USER:        (%%USRTAR%%)       = ($:\Users\Default)     ::>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;::       FOLDER WINDOWS:     (%%WINTAR%%)       = ($:\Windows)           ::>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;::       FOLDER BASE:        (%%DRVTAR%%)       = ($:)                   ::>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;::       REG-HIVE USER:     (%%HIVE_USER%%)     = (HKCU)                 ::>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;::       REG-HIVE SOFTWARE: (%%HIVE_SOFTWARE%%) = (HKLM\SOFTWARE)        ::>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;::       REG-HIVE SYSTEM:   (%%HIVE_SYSTEM%%)   = (HKLM\SYSTEM)          ::>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;:::::::::::::::::::::::::::::::START:OF:PACK:::::::::::::::::::::::::::::>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO.>>"%MAKER_FOLDER%\PACKAGE.CMD"
EXIT /B
:PACK_END
ECHO.>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;::::::::::::::::::::::::::::::::END:OF:PACK::::::::::::::::::::::::::::::>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::>>"%MAKER_FOLDER%\PACKAGE.CMD"
EXIT /B
:PACKEX_MENU_START
CALL:PACKEX_MENU_DISPLAY
SET PROMPT_SET=EXAMPLE&&CALL:PROMPT_SET&&IF NOT DEFINED EXAMPLE EXIT /B
ECHO [Project%MAKER_SLOT%] FOLDER WILL BE CLEARED&&ECHO.PRESS{Z}TO PROCEED&&SET "PROMPT_SET=CONFIRM"&&CALL:PROMPT_SET
IF NOT "%CONFIRM%"=="Z" EXIT /B
CALL:PACKEX_PROC
IF EXIST "%PROG_SOURCE%\SCRATCH" RD /S /Q "\\?\%PROG_SOURCE%\SCRATCH" >NUL 2>&1
SET EXAMPLE_MODE=&&SET EXAMPLE_NOPROMPT=
EXIT /B
:PACKEX_MENU_DISPLAY
CLS&&CALL:PAD_LINE&&ECHO.                      Example-Pack [%EXAMPLE_MODE%-MODE]&&CALL:PAD_LINE
ECHO  {E1} Create Local User-Account                           (SCRIPTED)
ECHO  {E2} Create Local Admin-Account                          (SCRIPTED)
ECHO  {E3} Import Firewall Rules.XML                           (SCRIPTED)
ECHO  {E4} UAC Prompt Always                                   (SCRIPTED)
ECHO  {E5} Taskmgr Prefs                                       (SCRIPTED)
ECHO  {E6} MSI Installer Example                               (SCRIPTED)
CALL:PAD_LINE&&ECHO                Press (Enter) to Return to Previous Menu
EXIT /B
:PACKEX_PROC
CALL:MOUNT_INT
SET PASS=&&FOR %%a in (E1 E2 E3 E4 E5 E6 DB1 DB2 DB3) DO (IF "%%a"=="%EXAMPLE%" SET PASS=1)
IF NOT "%PASS%"=="1" EXIT /B
FOR %%a in (PackName PackType PackDesc PackTag REG_KEY REG_VAL RUN_MOD REG_DAT) DO (CALL SET "%%a=NULL")
IF DEFINED MAKER_FOLDER RD /S /Q "%MAKER_FOLDER%">NUL 2>&1
IF NOT EXIST "%MAKER_FOLDER%" MD "%MAKER_FOLDER%">NUL 2>&1
CALL:PACK_VARS
IF "%EXAMPLE%"=="E1" CALL:PACKEX_NEWUSER
IF "%EXAMPLE%"=="E2" CALL:PACKEX_NEWADMIN
IF "%EXAMPLE%"=="E3" CALL:PACKEX_FIREWALL_IMPORT
IF "%EXAMPLE%"=="E4" CALL:PACKEX_UAC
IF "%EXAMPLE%"=="E5" CALL:PACKEX_TASKMGR_PREF
IF "%EXAMPLE%"=="E6" CALL:PACKEX_MSI_EXAMPLE
IF "%PackType%"=="SCRIPTED" CALL:PACK_END
CALL:PACK_MANIFEST>NUL 2>&1
IF DEFINED EXAMPLE CALL:MAKER_EDITOR
IF EXIST "%PROG_SOURCE%\ScratchPack" DISM /cleanup-MountPoints>NUL 2>&1
IF EXIST "%PROG_SOURCE%\ScratchPack" ATTRIB -R -S -H "%PROG_SOURCE%\ScratchPack" /S /D /L>NUL 2>&1
IF EXIST "%PROG_SOURCE%\ScratchPack" RD /S /Q "\\?\%PROG_SOURCE%\ScratchPack">NUL 2>&1
SET EXAMPLE=
EXIT /B
:PACKEX_NEWUSER
SET PackType=SCRIPTED&&SET PackName=Add_User&&SET PackDesc=Creates Local User-Account
ECHO       - USERNAME? -
ECHO     - ENTER USERNAME -
ECHO   - 0-9 A-Z - NO SPACES -
ECHO      (ENTER) TO CLEAR
SET PROMPT_SET=NEWUSER1&&CALL:PROMPT_SET
IF NOT DEFINED NEWUSER1 EXIT /B
ECHO;Net User %NEWUSER1% /add>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;Net User %NEWUSER1% /passwordreq:No>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;Net User %NEWUSER1% /passwordchg:No>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;Net Accounts /maxpwage:unlimited>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;WMIC USERACCOUNT WHERE Name='%NEWUSER1%' SET PasswordExpires=FALSE>>"%MAKER_FOLDER%\PACKAGE.CMD"
EXIT /B
:PACKEX_NEWADMIN
SET PackType=SCRIPTED&&SET PackName=Add_Admin&&SET PackDesc=Creates Local Admin-Account
ECHO       - USERNAME? -
ECHO     - ENTER USERNAME -
ECHO   - 0-9 A-Z - NO SPACES -
ECHO      (ENTER) TO CLEAR
SET PROMPT_SET=NEWUSER1&&CALL:PROMPT_SET
IF NOT DEFINED NEWUSER1 EXIT /B
ECHO;Net User %NEWUSER1% /add>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;Net User %NEWUSER1% /passwordreq:No>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;Net User %NEWUSER1% /passwordchg:No>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;Net Accounts /maxpwage:unlimited>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;Net localgroup Administrators %NEWUSER1% /add>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;WMIC USERACCOUNT WHERE Name='%NEWUSER1%' SET PasswordExpires=FALSE>>"%MAKER_FOLDER%\PACKAGE.CMD"
EXIT /B
:PACKEX_FIREWALL_IMPORT
SET PackType=SCRIPTED&&SET PackName=Firewall_Import&&SET PackDesc=Import Windows Firewall Config .XML
ECHO;::LIVE COMMAND, NEEDS TO BE APPLIED LIVE, SETUPCOMPLETE, OR RUNONCE>>"%MAKER_FOLDER%\PACKAGE.CMD"
NETSH advfirewall EXPORT "%MAKER_FOLDER%\FirewallPolicy.wfw"
ECHO;NETSH advfirewall IMPORT "FirewallPolicy.wfw">>"%MAKER_FOLDER%\PACKAGE.CMD"
EXIT /B
:PACKEX_UAC
SET PackType=SCRIPTED&&SET PackName=UAC_Prompt&&SET PackDesc=Enable UAC Always Prompt
ECHO;Reg.exe add "%%HIVE_SOFTWARE%%\Microsoft\Windows\CurrentVersion\Policies\SYSTEM" /v "ConsentPromptBehaviorAdmin" /t REG_DWORD /d "4" /f>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;Reg.exe add "%%HIVE_SOFTWARE%%\Microsoft\Windows\CurrentVersion\Policies\SYSTEM" /v "ConsentPromptBehaviorUser" /t REG_DWORD /d "1" /f>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;Reg.exe add "%%HIVE_SOFTWARE%%\Microsoft\Windows\CurrentVersion\Policies\SYSTEM" /v "ConsentPromptBehaviorAdmin" /t REG_DWORD /d "1" /f>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;Reg.exe add "%%HIVE_SOFTWARE%%\Microsoft\Windows\CurrentVersion\Policies\SYSTEM" /v "FilterAdministratorToken" /t REG_DWORD /d "1" /f>>"%MAKER_FOLDER%\PACKAGE.CMD"
EXIT /B
:PACKEX_TASKMGR_PREF
SET PackType=SCRIPTED&&SET PackName=TASKMGR_PREFS&&SET PackDesc=TASKMGR_PREFS
ECHO;::LIVE COMMAND, NEEDS TO BE APPLIED LIVE, SETUPCOMPLETE, OR RUNONCE>>"%MAKER_FOLDER%\PACKAGE.CMD"
Reg.exe EXPORT "%HIVE_USER%\Software\Microsoft\Windows\CurrentVersion\TaskManager" "%MAKER_FOLDER%\TASKMGR_PREF.REG"
ECHO;Reg.exe IMPORT TASK_PREF.REG>>"%MAKER_FOLDER%\PACKAGE.CMD"
EXIT /B
:PACKEX_MSI_EXAMPLE
SET PackType=SCRIPTED&&SET PackName=MSI_INSTALLER_EXAMPLE&&SET PackDesc=Example of a Scripted Pack MSI Installer
ECHO;::LIVE COMMAND, NEEDS TO BE APPLIED LIVE, SETUPCOMPLETE, OR RUNONCE>>"%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;::PUT MSI IN PACK FOLDER.>>%MAKER_FOLDER%\PACKAGE.CMD"
ECHO;"EXAMPLE.msi" /qn>>"%MAKER_FOLDER%\PACKAGE.CMD"
EXIT /B
